swagger: "2.0"
info:
  title: "Med App API"
  description: "API documentation for the Med App"
  version: "1.0.0"
schemes:
  - "http"
basePath: "/"
consumes:
  - "application/json"
produces:
  - "application/json"
